/**
 * Created by Administrator on 2015/12/8.
 */
$(document).ready(function(){
    $("#img1").click(function(){
        window.location.href="http://localhost:63342/sch_server/Torch-Schoolmate/sch_server/part_time_job.php";
        //跳转页面到创业帮扶
    });
    $("#img2").click(function(){
        window.location.href="#";
        //跳转到管经游戏
    });
    $("#img3").click(function(){
        window.location.href="#";
        //跳转到校内服务
    });
    $("#img4").click(function(){
        window.location.href="#";
        //跳转到求职助手
    });
    $("#img5").click(function(){
        window.location.href="#";
        //跳转到校友同城
    });
});
